name: course-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip:
    - transformers
    - datasets
    - peft
    - accelerate
    - bitsandbytes
    - trl
    - safetensors
    - lm-eval
    - gradio
    - flask
    - pgvector
    - sentence-transformers
    - langchain
    - langchain-core   
    - psycopg2-binary
    - pypdf
    - sqlalchemy
    
